#!/bin/bash

# Script to convert PNG icons to C header files with embedded byte data
# Usage: ./generate-icon-headers.sh

set -e

# Directories
ASSETS_DIR="assets"
SRC_DIR="src"
SOURCE_ICON="$ASSETS_DIR/icon-b-ev4d-1024.png"

# Icon sizes to generate
SIZES=(48 128 512)

# Check if source icon exists
if [ ! -f "$SOURCE_ICON" ]; then
    echo "Error: Source icon not found: $SOURCE_ICON"
    exit 1
fi

# Check if ImageMagick is available (prefer 'magick' over deprecated 'convert')
if command -v magick &> /dev/null; then
    CONVERT_CMD="magick"
elif command -v convert &> /dev/null; then
    CONVERT_CMD="convert"
else
    echo "Error: ImageMagick not found. Please install ImageMagick."
    exit 1
fi

echo "Generating icon header files..."

# Create temporary directory for resized icons
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

for SIZE in "${SIZES[@]}"; do
    TEMP_PNG="$TEMP_DIR/icon-${SIZE}.png"
    HEADER_FILE="$SRC_DIR/icon-${SIZE}.h"
    VAR_NAME="icon_${SIZE}_png"

    echo "  Processing ${SIZE}x${SIZE} icon..."

    # Resize PNG using ImageMagick
    $CONVERT_CMD "$SOURCE_ICON" -resize ${SIZE}x${SIZE} "$TEMP_PNG"

    # Generate header file
    cat > "$HEADER_FILE" << EOF
/*
 * Embedded PNG icon data for ${SIZE}x${SIZE} printer icon
 * Auto-generated by scripts/generate-icon-headers.sh
 * Do not edit manually!
 */

#ifndef ICON_${SIZE}_H
#define ICON_${SIZE}_H

#include <stddef.h>

EOF

    # Convert PNG to C byte array
    echo "static const unsigned char ${VAR_NAME}_data[] = {" >> "$HEADER_FILE"

    # Use xxd to convert binary to hex array
    xxd -i < "$TEMP_PNG" | sed 's/^/  /' >> "$HEADER_FILE"

    echo "};" >> "$HEADER_FILE"

    # Get file size (BSD stat on macOS uses -f, GNU stat uses -c)
    if stat -f%z "$TEMP_PNG" &>/dev/null; then
        FILE_SIZE=$(stat -f%z "$TEMP_PNG")
    else
        FILE_SIZE=$(stat -c%s "$TEMP_PNG")
    fi

    # Add size constant
    cat >> "$HEADER_FILE" << EOF

static const size_t ${VAR_NAME}_size = ${FILE_SIZE};

#endif /* ICON_${SIZE}_H */
EOF

    echo "    Generated: $HEADER_FILE (${FILE_SIZE} bytes)"
done

echo "Icon header generation complete!"
echo ""
echo "Generated files:"
for SIZE in "${SIZES[@]}"; do
    echo "  - src/icon-${SIZE}.h"
done
